language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - poetry install --dev
before_script:
  - poetry run unittest tests/**
script:
  - poetry build
  - poetry publish -u $USERNAME -p $PASSWORD
